# Generated by Django 5.2.1 on 2025-05-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MQTTConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker_address', models.CharField(default='localhost', max_length=255)),
                ('broker_port', models.IntegerField(default=1883)),
                ('set_topic', models.CharField(max_length=255)),
                ('state_topic', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Shutter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relay_open', models.IntegerField(default=1)),
                ('relay_close', models.IntegerField(default=2)),
                ('open_duration', models.FloatField(default=5.0)),
                ('close_duration', models.FloatField(default=5.0)),
                ('current_state', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
            ],
        ),
    ]
