# Generated by Django 5.2.1 on 2025-05-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shutters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shutter',
            name='input_close',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shutter',
            name='input_open',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
