# Generated by Django 5.2.1 on 2025-05-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shutters', '0002_shutter_input_close_shutter_input_open'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shutter',
            name='close_duration',
            field=models.FloatField(default=30.0),
        ),
        migrations.AlterField(
            model_name='shutter',
            name='current_state',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('inprogress', 'In progress'), ('unknown', 'Unknown')], default='unknown', max_length=12),
        ),
        migrations.AlterField(
            model_name='shutter',
            name='open_duration',
            field=models.FloatField(default=30.0),
        ),
    ]
