# Generated by Django 5.2.1 on 2025-05-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shutters', '0003_alter_shutter_close_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shutter',
            name='current_state',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('open', 'Open'), ('closed', 'Closed'), ('opening', 'Opening'), ('closing', 'Closing')], default='unknown', max_length=12),
        ),
    ]
